const data = [
  {
    id: "1",
    image: "blog_img_1.jpg",
    title: "Ninja",
    description:
      "Ninja (aka Shinobi) were the specialised assassins, saboteurs, and secret agents of medieval Japanese warfare who were highly-trained proponents of the martial arts, especially what later became known as ninjutsu or 'the art of the ninja'. These special forces were adept at disguise, deception, and assaulting enemy positions and strongholds, usually at night when they moved like shadows in their traditional dark clothing. Employed from the 15th century CE onwards, ninjas, because of their lengthy secret training in specialised schools and mysterious anonymity, have acquired a perhaps exaggerated reputation for fantastic feats and weapons play, which makes them perfect characters for many modern comic books and computer games.",
    text: `
    <p>Ninja (aka Shinobi) were the specialised assassins, saboteurs, and secret agents of medieval Japanese warfare who were highly-trained proponents of the martial arts, especially what later became known as ninjutsu or 'the art of the ninja'. These special forces were adept at disguise, deception, and assaulting enemy positions and strongholds, usually at night when they moved like shadows in their traditional dark clothing. Employed from the 15th century CE onwards, ninjas, because of their lengthy secret training in specialised schools and mysterious anonymity, have acquired a perhaps exaggerated reputation for fantastic feats and weapons play, which makes them perfect characters for many modern comic books and computer games.</p>
    <h2>Martial Arts & Ninjutsu</h2>
    <p>In medieval Japan, there were no fewer than 18 individual martial arts (bugei or bujutsu). Besides the more familiar ones which are still practised today such as judo, jujutsu and kendo, there were those involving horsemanship and swimming. One of the 18 was the art of the ninja or ninjutsu, which developed during the Edo Period (1603-1868 CE). However, ninjas as military special forces had been in operation since the 15th century CE and the Warring States Period (aka Sengoku Jidai, 1467-1568 CE) when the factious infighting that beset Japan required reconnaissance, intelligence and spying in order to ascertain who exactly one's enemies were or might be in the near future.</p>
    <h2>Training</h2>
    <p>The earliest approach to ninja training was taken by particular families of samurai warriors who passed on their skills from father or master (sensei) to son. These became the famous ninja families and explain why certain localities established long traditions of producing the specialised warriors. From childhood, a future ninja would learn to ride, swim, and handle weapons of all kinds. From the 15th century CE, ninjas were being trained in special camps which might involve entire villages. Some schools became especially famous such as the Iga and Koga schools. As leaders did not want rivals copying their tactics, all training was done orally lest written records fall into the wrong hands.</p>
    <p>A ninja was trained to be physically fit and nimbly athletic; jumping from heights and across moats and other obstacles was a particularly useful skill and is probably the origin of the legends involving flying ninjas. In addition, they were also trained to work in acrobat-like teams so that they could use each other to climb greater heights. Ninjas could also throw grappling hooks with precision, scale up and down ropes and collapsible ladders, and enter places closed to less-skilled operatives. Ninjas could create spyholes using pocket folding saws and gouging tools. They could impede pursuers by throwing down makibishi (caltrops - metal clusters of points). Ninjas were taught such useful skills as concealing oneself in various terrains, survival skills to live off the country, how to read topography and maps, understand indications of weather changes, use explosives, securely tie up captives, mix poisons, destroy a building by fire, and, for when things did not go well on a mission, the arts of escape and medicine.</p>
    <h2>Ninja Costume</h2>
    <p>Although no medieval texts actually describe in detail a ninja's outfit, the most usual depiction in Japanese art from the early 19th century CE has them clad all in black. This would seem to be the most obvious colour choice because most of their work was done at night. It is also a convention of Japanese performance arts that a character wears black to show the audience that he or she is invisible. However, ninjas did sometimes wear chain mail or armour of metal plates sewn onto fabric and, as they were meant to blend into their surroundings, they sometimes wore camouflage, disguises (as beggars, monks or wandering musicians, for example) and even the costume of their enemies when required. The classic ninja outfit consists of trousers, gaiters, a jacket, a belt, a head cover and a face cover all in soft material that did not impede movement and which had no dangling parts that might catch on anything. Soft shoes were worn which were more like socks (tabi) with the big toe divided from the rest of the toes and a reinforced sole; simple knotted-rope sandals (waraji) might be worn over these to provide a better grip for climbing.</p>
    `,
    author: "Mark Cartwright",
  },
  {
    id: "2",
    image: "blog_img_2.jpg",
    title: "Spartans",
    description:
      "Sparta was a warrior society in ancient Greece that reached the height of its power after defeating rival city-state Athens in the Peloponnesian War (431-404 B.C.). Spartan culture was centered on loyalty to the state and military service. Spartan boys entered a rigorous state-sponsored education, military training and socialization program. Known as the Agoge, the system emphasized duty, discipline and endurance. Although Spartan women were not active in the military, they were educated and enjoyed more status and freedom than other Greek women.",
    text: `
    <p>Sparta was a warrior society in ancient Greece that reached the height of its power after defeating rival city-state Athens in the Peloponnesian War (431-404 B.C.). Spartan culture was centered on loyalty to the state and military service. Spartan boys entered a rigorous state-sponsored education, military training and socialization program. Known as the Agoge, the system emphasized duty, discipline and endurance. Although Spartan women were not active in the military, they were educated and enjoyed more status and freedom than other Greek women.</p>
    <h2>Sparta Life</h2>
    <p>Sparta, also known as Lacedaemon, was an ancient Greek city-state located primarily in a region of southern Greece called Laconia. The population of Sparta consisted of three main groups: the Spartans, or Spartiates, who were full citizens; the Helots, or serfs/slaves; and the Perioeci, who were neither slaves nor citizens. The Perioeci, whose name means “dwellers-around,” worked as craftsmen and traders, and made weapons for the Spartans.    </p>
    <p>All healthy male Spartan citizens participated in the compulsory state-sponsored education system, the Agoge, which emphasized obedience, endurance, courage and self-control. Spartan men devoted their lives to military service, and lived communally well into adulthood. A Spartan was taught that loyalty to the state came before everything else, including one’s family.    </p>
    <p>The Helots, whose name means “captives,” were fellow Greeks, originally from Laconia and Messenia, who had been conquered by the Spartans and turned into slaves. The Spartans’ way of life would not have been possible without the Helots, who handled all the day-to-day tasks and unskilled labor required to keep society functioning: They were farmers, domestic servants, nurses and military attendants.    </p>
    <p> Spartans, who were outnumbered by the Helots, often treated them brutally and oppressively in an effort to prevent uprisings. Spartans would humiliate the Helots by doing such things as forcing them to get debilitatingly drunk on wine and then make fools of themselves in public. (This practice was also intended to demonstrate to young people how an adult Spartan should never act, as self-control was a prized trait.) Methods of mistreatment could be far more extreme: Spartans were allowed to kill Helots for being too smart or too fit, among other reasons.</p>
    <h2>The Spartan Military</h2>
    <p>Unlike such Greek city-states as Athens — a center for the arts, learning and philosophy — Sparta was centered on a warrior culture. Male Spartan citizens were allowed only one occupation: soldier. Indoctrination into this lifestyle began early.</p>
    <p>Spartan boys started their military training at age 7, when they left home and entered the Agoge. The boys lived communally under austere conditions. They were subjected to continual physical, competitions (which could involve violence), given meager rations and expected to become skilled at stealing food, among other survival skills.</p>
    <h2>Spartan Armor, Shield and Helmet</h2>
    <p>No one soldier was considered superior to another. Going into battle, a Spartan soldier, or hoplite, wore a large bronze helmet, breastplate and ankle guards, and carried a round shield made of bronze and wood, a long spear and sword. Spartan warriors were also known for their long hair and red cloaks.</p>
    <p>The Spartans’ constant military drilling and discipline made them skilled at the ancient Greek style of fighting in a phalanx formation. In the phalanx, the army worked as a unit in a close, deep formation, and made coordinated mass maneuvers.</p>
    <h2>Spartan Women </h2>
    <p>Spartan women had a reputation for being independent-minded, and enjoyed more freedoms and power than their counterparts throughout ancient Greece. While they played no role in the military, female Spartans often received a formal education, although separate from boys and not at boarding schools.</p>
    <p>In part to attract mates, females engaged in athletic competitions, including javelin-throwing and wrestling, and also sang and danced competitively. As adults, Spartan women were allowed to own and manage property. Additionally, they were typically unencumbered by domestic responsibilities such as cooking, cleaning and making clothing, tasks which were handled by the Helots.</p>
    <p>Marriage was important to Spartans, as the state put pressure on people to have male children who would grow up to become citizen-warriors, and to replace those who died in battle. Men who delayed marriage were publicly shamed, while those who fathered multiple sons could be rewarded.</p>
    `,
    author: "History.com",
  },
  {
    id: "3",
    image: "blog_img_3.jpg",
    title: "Vikings",
    description:
      "Vikings history is as extensive as the people it studies. The seafaring Vikings (in Danish, the Vikinger) were a group of people that came from the Scandinavian countries of Norway, Denmark, and Sweden. They made an enduring name for themselves in the 8th through the 11th centuries for being tactical warriors, smart traders, and daring explorers. In fact, they arrived in America 1,000 years before Columbus ever did, and archeologists have found some of their remnants scattered as far east as Russia. This is the true story of Vikings history.",
    text: `
    <p>Vikings history is as extensive as the people it studies. The seafaring Vikings (in Danish, the Vikinger) were a group of people that came from the Scandinavian countries of Norway, Denmark, and Sweden. They made an enduring name for themselves in the 8th through the 11th centuries for being tactical warriors, smart traders, and daring explorers. In fact, they arrived in America 1,000 years before Columbus ever did, and archeologists have found some of their remnants scattered as far east as Russia. This is the true story of Vikings history.</p>
    <h2>Who Were the Vikings?</h2>
    <p>The true Vikings history is fascinating. Simply put, the Vikings were Norwegians, Swedes and Danes, men who were usually farmers, traders, blacksmiths, and craftsmen. For various reasons, they took to raiding towns, churches and monasteries. Many of the places they attacked were on the coasts as they were easiest to reach. With their swift and easily landed ships, the Vikings could quickly swarm over the communities, killing and looting, and just as fast return to their ships and leave. They were gone before any defense or counter-attack could be made.</p>
    <p>Strangely enough, for most of the men who went a-viking, it was only part time. When a Viking wasn’t busy farming, planting crops, for instance, they left their farms and went raiding. They often returned in time for harvest in the fall. Raiding was very profitable, however, and many farmers became full time pirates and raiders.</p>
    <p>The people called Vikings were also fearless explorers who actually reached North America, making them the first Europeans to discover America. They settled Iceland and tried to colonize Greenland. They were also shrewd and competent traders and merchants. They traded all the goods of the north – furs, amber, iron and timber – for all the goods of the south – silver, gold, silks and spices. And all along the trade routes, the Vikings traded in slaves. Read our articles to explore these aspects of the incredible culture of these intrepid and dangerous men. This is the true story of Vikings history.</p>
    <h2>Impact of the Viking Age</h2>
    <p>The Scandinavians changed the history of Ireland, England, Russia and other European countries. They established new territories in Iceland, Greenland and temporarily, North America. From A.D. 793 to 1066, Vikings raided, traded, challenged, conquered and settled in many lands. Popular movies and novels give you a glimpse into their lives, but usually show only a part of the impact these energetic people had on the known world of the time. Reading here will give you a much better grasp of their impact on other cultures.</p>
    <h2>Viking Culture</h2>
    <p>We will explore Viking culture and the structure of their society, the roles of men and women and the daily life of the time. Here you will find articles on women and children in that warrior culture. You’ll discover how they lived, what their homes were like and what they did for fun. Examine their stunning artwork and jewelry, as well as their weaponry and armor. The brave among you can read about a Viking raid from the point of view of the victims. Come with us as we take ship with Vikings to explore the new lands of Iceland and Vinland. We’ll explain Viking ship building and their remarkable navigation skills. Find out what your name would look like in runes, the Viking writing system. Explore with us the mythology and literature of the Viking era.</p>
    <h2>Vikings History — From Pagans to Christians</h2>
    <p>While Charlemagne “converted” pagans to Christianity by the sword, the conversion of Vikings to Christianity occurred without violence for the most part. In the early Viking Age, Viking traders noted that they suffered losses in trade contracts and deals because the other party was Christian. Christian traders tended to give more business and better deals to other Christians, discriminating against pagans and Muslims. A Viking trader might then wear a cross when he was among Christians only to change it back to his usual Thor’s hammer upon returning home. As long as the Viking trader wasn’t baptized, he could practice both religions, a common practice in Scandinavia for the next few centuries.</p>
    <p>At first, the Viking Norse didn’t take to Christianity. They loved their own gods and were content with them. English and Frankish Christian priests and monks had begun missionary tours to the Viking lands from the 700s to 800s. However, the conversion of the Vikings took place over centuries. Even when a Danish or Swedish king became Christian and proclaimed his people were Christian, many still practiced their pagan ways and held to the old gods. By the end of the Viking Age, however, most Vikings had become fully Christian and were baptized and buried in that faith.</p>
    `,
    author: "Salem Media",
  },
];

export default data;
